# Generated by Django 5.2.6 on 2026-09-07 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер замовлення')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('city', models.CharField(max_length=120, verbose_name='Місто')),
                ('np_type', models.CharField(choices=[('warehouse', 'Відділення'), ('postomat', 'Поштомат'), ('address', 'Адресна доставка')], max_length=16, verbose_name='Тип отримання')),
                ('np_point', models.CharField(max_length=255, verbose_name='Відділення / адреса')),
                ('payment_method', models.CharField(choices=[('monobank', 'Monobank')], default='monobank', max_length=16, verbose_name='Спосіб оплати')),
                ('payment_status', models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('failed', 'Помилка оплати')], default='pending', max_length=16, verbose_name='Статус оплати')),
                ('monobank_invoice_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Monobank invoiceId')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('confirmed', 'Підтверджено'), ('shipped', 'Відправлено'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], default='new', max_length=16, verbose_name='Статус замовлення')),
                ('total_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума, UAH')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=32, verbose_name='SKU (на момент замовлення)')),
                ('product_name', models.CharField(max_length=200, verbose_name='Назва (на момент замовлення)')),
                ('unit_price_uah', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за од., UAH')),
                ('qty', models.PositiveSmallIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
    ]
