# Generated by Django 5.2.6 on 2026-09-07 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('capacity_wh', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ємність, Вт·год')),
                ('output_power_w', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вихідна потужність, Вт')),
                ('battery_type', models.CharField(blank=True, choices=[('lifepo4', 'LiFePO4'), ('li_ion', 'Li-ion (NMC)')], max_length=16, verbose_name='Тип акумулятора')),
                ('outputs', models.TextField(blank=True, help_text='Наприклад: 3×AC, 2×USB-C PD100W, 2×USB-A, DC', verbose_name="Роз'єми виходу")),
                ('charging', models.TextField(blank=True, help_text='Наприклад: AC 0-80% за 1 год, сонячна панель до 200Вт', verbose_name='Варіанти заряджання')),
                ('features', models.TextField(blank=True, help_text='UPS, застосунок, LED-фонарик тощо — через кому', verbose_name='Особливості')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вага, кг')),
                ('dimensions', models.CharField(blank=True, max_length=50, verbose_name='Габарити (ДxШxВ, мм)')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price_eur_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Закупівельна ціна netto, EUR')),
                ('price_uah', models.DecimalField(blank=True, decimal_places=2, help_text='Порожньо, доки не підтверджено курс і націнку — товар неактивний.', max_digits=10, null=True, verbose_name='Роздрібна ціна, UAH')),
                ('old_price_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна (для акції), UAH')),
                ('is_active', models.BooleanField(default=False, help_text='Автоматично False, доки немає ціни UAH — вмикається вручну після перевірки.', verbose_name='Активний (видимий на сайті)')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хіт продажів')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_price_confirmed', models.BooleanField(default=False, help_text='SEC-02: без цього товар не можна продавати.', verbose_name='Ціна підтверджена')),
                ('is_specs_confirmed', models.BooleanField(default=False, verbose_name='Характеристики звірені з сайту виробника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-is_hit', 'brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt-текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('is_placeholder', models.BooleanField(default=False, verbose_name='Заглушка (немає реального фото)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товарів',
                'ordering': ['order', 'id'],
            },
        ),
    ]
