# Generated by Django 5.2.6 on 2026-09-21 09:08

import core.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[core.utils.images.validate_image], verbose_name='Зображення'),
        ),
    ]
