# Generated by Django 5.2.6 on 2026-09-21 09:19

import catalog.models
import core.utils.documents
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage_image_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manual', 'Інструкція'), ('certificate', 'Сертифікат')], max_length=16, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Назва')),
                ('file', models.FileField(upload_to=catalog.models._product_document_upload_to, validators=[core.utils.documents.validate_pdf], verbose_name='PDF')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Документ товару',
                'verbose_name_plural': 'Документи товару',
                'ordering': ['kind', 'order', 'id'],
            },
        ),
    ]
