# Generated by Django 5.2.6 on 2026-09-30 13:42

from django.db import migrations, models


def backfill_search_text(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    from catalog.search import build_search_fields

    for product in Product.objects.select_related("brand"):
        Product.objects.filter(pk=product.pk).update(**build_search_fields(product))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_name',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Нормалізована назва для пошуку'),
        ),
        migrations.AddField(
            model_name='product',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Нормалізований текст для пошуку'),
        ),
        migrations.RunPython(backfill_search_text, migrations.RunPython.noop),
    ]
