# Generated by Django 5.2.6 on 2026-10-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+38 (067) 555-12-34', max_length=32, verbose_name='Телефон'),
        ),
    ]
